"""Open-source interval tool for TRUST-TC.

The tool intentionally starts with an existing-result mode. It accepts
apparent TRT estimates produced by a conventional interpretation model and
maps them through the calibrated transformation-uncertainty factors already
generated by the TRUST-TC numerical benchmark.
"""

from __future__ import annotations

from dataclasses import dataclass
from importlib import resources
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd


CALIBRATION_VERSION = "0.1.0"
CALIBRATION_DOMAIN = "full_3d"
PACKAGED_CALIBRATION = "full3d_production_correction_factor_distribution.csv"

MODEL_TO_PATHWAY = {
    "A0": "A0",
    "A1": "A1",
    "A2": "A2",
    "A3": "A3",
    "LT-ILS": "A0",
    "LATE-TIME ILS": "A0",
    "LATE TIME ILS": "A0",
    "ILS": "A1",
    "EXACT ILS": "A1",
    "ICS": "A2",
    "CYLINDRICAL": "A2",
    "CYLINDRICAL SOURCE": "A2",
    "FLS": "A3",
    "FINITE LINE SOURCE": "A3",
}

PATHWAY_TO_MODEL = {
    "A0": "LT-ILS",
    "A1": "ILS",
    "A2": "ICS",
    "A3": "FLS",
}

PARAMETER_ALIASES = {
    "lambda": "lambda",
    "conductivity": "lambda",
    "thermal_conductivity": "lambda",
    "C": "C",
    "heat_capacity": "C",
    "volumetric_heat_capacity": "C",
    "alpha": "alpha",
    "diffusivity": "alpha",
    "thermal_diffusivity": "alpha",
}


@dataclass(frozen=True)
class CalibrationFactors:
    p05: float
    p50: float
    p95: float
    reliability_class: str
    warning: str = ""


def normalize_model(value: object) -> tuple[str, str]:
    """Return internal pathway id and public model name."""

    text = str(value).strip()
    key = text.upper()
    pathway_id = MODEL_TO_PATHWAY.get(key)
    if pathway_id is None:
        raise ValueError(f"unsupported_model: {value!r}")
    return pathway_id, PATHWAY_TO_MODEL[pathway_id]


def normalize_parameter(value: object) -> str:
    key = str(value).strip()
    parameter = PARAMETER_ALIASES.get(key) or PARAMETER_ALIASES.get(key.lower())
    if parameter is None:
        raise ValueError(f"unsupported_parameter: {value!r}")
    return parameter


@dataclass(frozen=True)
class CalibrationTable:
    data: pd.DataFrame
    source: Path
    domain: str = CALIBRATION_DOMAIN
    version: str = CALIBRATION_VERSION
    mesh_gate_status: str = ""
    numerical_stability_status: str = ""


def _filter_calibration(table: pd.DataFrame, source: Path, *, domain: str | None = None) -> CalibrationTable:
    required = {
        "pathway_id",
        "p05_factor_lambda",
        "p50_factor_lambda",
        "p95_factor_lambda",
    }
    missing = required.difference(table.columns)
    if missing:
        raise ValueError(f"Calibration table is missing required columns: {sorted(missing)}")
    if "calibration_domain" in table.columns:
        domains = table["calibration_domain"].astype(str).str.lower()
        filtered = table[domains.isin(["full_3d", "full_3d_production"])].copy()
    elif "truth_type" in table.columns:
        filtered = table[table["truth_type"].astype(str).isin(["F3D", "F3"])].copy()
    else:
        filtered = table.copy()
    if filtered.empty:
        raise ValueError("Calibration table does not contain a usable TRUST-TC calibration domain.")
    inferred_domain = domain or ("full_3d" if "full3d" in str(source).lower() else CALIBRATION_DOMAIN)
    version = CALIBRATION_VERSION
    if "calibration_version" in filtered.columns:
        versions = filtered["calibration_version"].dropna().astype(str)
        if not versions.empty:
            version = str(versions.iloc[0])
    mesh_gate_status = ""
    if "mesh_gate_status" in filtered.columns:
        statuses = filtered["mesh_gate_status"].dropna().astype(str)
        if not statuses.empty:
            mesh_gate_status = str(statuses.iloc[0])
    numerical_stability_status = ""
    if "numerical_stability_status" in filtered.columns:
        statuses = filtered["numerical_stability_status"].dropna().astype(str)
        if not statuses.empty:
            numerical_stability_status = str(statuses.iloc[0])
    return CalibrationTable(
        data=filtered,
        source=source,
        domain=inferred_domain,
        version=version,
        mesh_gate_status=mesh_gate_status,
        numerical_stability_status=numerical_stability_status,
    )


def _read_calibration(root: Path) -> CalibrationTable:
    production_summary = root / "outputs" / "full3d_production" / "full3d_production_correction_factor_distribution.csv"
    recalibrated_summary = root / "outputs" / "full3d_recalibrated" / "full3d_recalibrated_correction_factor_distribution.csv"
    full3d_summary = root / "outputs" / "full3d_framework" / "full3d_correction_factor_distribution.csv"
    depth_summary = root / "outputs" / "a0_a3_tu" / "a0_a3_tu_summary_by_depth_block.csv"
    truth_summary = root / "outputs" / "a0_a3_tu" / "a0_a3_tu_summary_by_truth_type.csv"
    if production_summary.exists():
        table = pd.read_csv(production_summary)
        source = production_summary
        return _filter_calibration(table, source, domain="full_3d_production")
    if recalibrated_summary.exists():
        table = pd.read_csv(recalibrated_summary)
        source = recalibrated_summary
        return _filter_calibration(table, source, domain="full_3d")
    if full3d_summary.exists():
        table = pd.read_csv(full3d_summary)
        source = full3d_summary
        return _filter_calibration(table, source, domain="full_3d")
    if depth_summary.exists():
        table = pd.read_csv(depth_summary)
        source = depth_summary
    elif truth_summary.exists():
        table = pd.read_csv(truth_summary)
        source = truth_summary
    else:
        resource = resources.files("trust_tc").joinpath("calibration", PACKAGED_CALIBRATION)
        if not resource.is_file():
            raise FileNotFoundError("No TRUST-TC calibration summary table was found.")
        with resource.open("rb") as handle:
            table = pd.read_csv(handle)
        source = Path(str(resource))
        return _filter_calibration(table, source, domain="full_3d_production")
    return _filter_calibration(table, source, domain="legacy_calibration")


def _load_calibration(root: Path, calibration_csv: Path | str | None, calibration_domain: str | None = None) -> CalibrationTable:
    if calibration_csv is None:
        return _read_calibration(root)
    source = Path(calibration_csv)
    if not source.is_absolute():
        source = root / source
    if not source.exists():
        raise FileNotFoundError(f"Calibration table not found: {source}")
    domain = calibration_domain or ("full_3d" if "full3d" in str(source).lower() else None)
    return _filter_calibration(pd.read_csv(source), source, domain=domain)


def _finite_or_nan(values: Iterable[float]) -> list[float]:
    out: list[float] = []
    for value in values:
        numeric = pd.to_numeric(value, errors="coerce")
        if pd.notna(numeric) and np.isfinite(float(numeric)):
            out.append(float(numeric))
    return out


def _factor_from_rows(rows: pd.DataFrame, parameter: str) -> CalibrationFactors:
    if parameter == "lambda":
        cols = ("p05_factor_lambda", "p50_factor_lambda", "p95_factor_lambda")
    elif parameter == "C":
        cols = ("p05_factor_C", "p50_factor_C", "p95_factor_C")
    elif parameter == "alpha":
        lambda_cols = ("p05_factor_lambda", "p50_factor_lambda", "p95_factor_lambda")
        c_cols = ("p05_factor_C", "p50_factor_C", "p95_factor_C")
        missing_c = rows[list(c_cols)].apply(pd.to_numeric, errors="coerce").isna().all().all()
        if missing_c:
            return CalibrationFactors(np.nan, np.nan, np.nan, "D", "parameter_not_identifiable")
        lambda_p05 = float(pd.to_numeric(rows[lambda_cols[0]], errors="coerce").median())
        lambda_p50 = float(pd.to_numeric(rows[lambda_cols[1]], errors="coerce").median())
        lambda_p95 = float(pd.to_numeric(rows[lambda_cols[2]], errors="coerce").median())
        c_p05 = float(pd.to_numeric(rows[c_cols[0]], errors="coerce").median())
        c_p50 = float(pd.to_numeric(rows[c_cols[1]], errors="coerce").median())
        c_p95 = float(pd.to_numeric(rows[c_cols[2]], errors="coerce").median())
        return CalibrationFactors(
            p05=lambda_p05 / c_p95,
            p50=lambda_p50 / c_p50,
            p95=lambda_p95 / c_p05,
            reliability_class=_median_reliability_class(rows),
        )
    else:
        raise ValueError(f"Unsupported parameter: {parameter}")

    factors = [float(pd.to_numeric(rows[col], errors="coerce").median()) for col in cols]
    if not _finite_or_nan(factors):
        return CalibrationFactors(np.nan, np.nan, np.nan, "D", "parameter_not_identifiable")
    return CalibrationFactors(
        p05=factors[0],
        p50=factors[1],
        p95=factors[2],
        reliability_class=_median_reliability_class(rows),
    )


def _median_reliability_class(rows: pd.DataFrame) -> str:
    if "recommended_reliability_class_candidate" not in rows:
        return "C"
    classes = rows["recommended_reliability_class_candidate"].dropna().astype(str)
    if classes.empty:
        return "C"
    order = {"A": 0, "B": 1, "C": 2, "D": 3}
    ranked = sorted((order.get(value[:1].upper(), 2), value[:1].upper()) for value in classes)
    return ranked[len(ranked) // 2][1]


def lookup_calibration(
    calibration: pd.DataFrame,
    pathway_id: str,
    parameter: str,
    support_id: str | None = None,
) -> CalibrationFactors:
    rows = calibration[calibration["pathway_id"].eq(pathway_id)]
    if support_id and "support_id" in rows:
        support_rows = rows[rows["support_id"].astype(str).str.lower().eq(str(support_id).lower())]
        if not support_rows.empty:
            rows = support_rows
    if rows.empty:
        return CalibrationFactors(np.nan, np.nan, np.nan, "D", "outside_calibration_domain")
    return _factor_from_rows(rows, parameter)


def design_reference_factor(parameter: str, factors: CalibrationFactors) -> float:
    if not np.isfinite(factors.p05) or not np.isfinite(factors.p50) or not np.isfinite(factors.p95):
        return np.nan
    if parameter == "lambda":
        return max(1.0, 1.0 / factors.p05)
    low_spread = factors.p50 / factors.p05 if factors.p05 > 0 else np.nan
    high_spread = factors.p95 / factors.p50 if factors.p50 > 0 else np.nan
    return float(np.nanmax([1.0, low_spread, high_spread]))


def run_interval_mode(
    input_csv: Path | str,
    output_csv: Path | str,
    *,
    root: Path | str | None = None,
    calibration_csv: Path | str | None = None,
    calibration_domain: str | None = None,
) -> pd.DataFrame:
    """Convert existing apparent TRT estimates into uncertainty intervals."""

    root_path = Path(root) if root is not None else Path.cwd()
    input_path = Path(input_csv)
    output_path = Path(output_csv)
    calibration = _load_calibration(root_path, calibration_csv, calibration_domain=calibration_domain)

    required = {"site", "depth_interval", "interpretation_model", "parameter", "apparent_estimate"}
    input_table = pd.read_csv(input_path)
    missing = required.difference(input_table.columns)
    if missing:
        raise ValueError(f"Input table is missing required columns: {sorted(missing)}")

    output_rows: list[dict[str, object]] = []
    for _, row in input_table.iterrows():
        pathway_id, model_name = normalize_model(row["interpretation_model"])
        parameter = normalize_parameter(row["parameter"])
        apparent = pd.to_numeric(row["apparent_estimate"], errors="coerce")
        support_id = row.get("support_id", None)
        factors = lookup_calibration(calibration.data, pathway_id, parameter, support_id=support_id)
        warning = factors.warning
        if pd.isna(apparent):
            warning = ";".join(filter(None, [warning, "missing_apparent_estimate"]))

        interval_p05 = float(apparent) * factors.p05 if pd.notna(apparent) else np.nan
        corrected_median = float(apparent) * factors.p50 if pd.notna(apparent) else np.nan
        interval_p95 = float(apparent) * factors.p95 if pd.notna(apparent) else np.nan
        design_factor = design_reference_factor(parameter, factors)

        if "reliability_class" in input_table.columns and pd.notna(row.get("reliability_class")):
            reliability = str(row["reliability_class"])[:1].upper()
        else:
            reliability = factors.reliability_class

        output_rows.append(
            {
                "site": row["site"],
                "depth_interval": row["depth_interval"],
                "interpretation_model": model_name,
                "parameter": parameter,
                "apparent_estimate": apparent,
                "corrected_median": corrected_median,
                "interval_p05": interval_p05,
                "interval_p95": interval_p95,
                "correction_factor_p50": factors.p50,
                "correction_factor_p05": factors.p05,
                "correction_factor_p95": factors.p95,
                "reliability_class": reliability,
                "design_reference_factor": design_factor,
                "warning_flag": warning,
                "calibration_source": str(calibration.source),
                "calibration_domain": calibration.domain,
                "calibration_version": calibration.version,
                "mesh_gate_status": calibration.mesh_gate_status,
                "numerical_stability_status": calibration.numerical_stability_status,
            }
        )

    result = pd.DataFrame(output_rows)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    result.to_csv(output_path, index=False)
    return result


def build_examples_from_field_outputs(root: Path | str) -> dict[str, Path]:
    """Create example input files from existing field interpretation outputs."""

    root_path = Path(root)
    examples_dir = root_path / "examples"
    examples_dir.mkdir(parents=True, exist_ok=True)
    field = pd.read_csv(root_path / "outputs" / "field_sop" / "field_parameter_soft_observation_intervals.csv")
    field = field[pd.to_numeric(field["observed_value"], errors="coerce").notna()].copy()
    mapping = {"A0": "LT-ILS", "A1": "ILS", "A2": "ICS", "A3": "FLS"}
    field["interpretation_model"] = field["pathway_id"].map(mapping)
    field["apparent_estimate"] = field["observed_value"]
    field["depth_interval"] = field["depth_block_id"].astype(str)
    field["support_id"] = np.where(field["site"].astype(str).eq("Fukuoka"), "whole", "middle")
    columns = [
        "site",
        "depth_interval",
        "interpretation_model",
        "parameter",
        "apparent_estimate",
        "support_id",
        "reliability_class",
    ]
    example = field[columns].head(12)
    ntu = field[field["site"].astype(str).str.contains("NTU", case=False, na=False)][columns].head(24)
    fukuoka = field[field["site"].astype(str).str.contains("Fukuoka", case=False, na=False)][columns]
    paths = {
        "example": examples_dir / "example_fitted_results.csv",
        "ntu": examples_dir / "ntu_tool_demo.csv",
        "fukuoka": examples_dir / "fukuoka_tool_demo.csv",
    }
    example.to_csv(paths["example"], index=False)
    ntu.to_csv(paths["ntu"], index=False)
    fukuoka.to_csv(paths["fukuoka"], index=False)
    return paths
